export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";

export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";

export const GET_MEMBERSHIPS = "GET_MEMBERSHIPS";

export const SEND_RESET_EMAIL = "SEND_RESET_EMAIL";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const GET_FAQS = "GET_FAQS";

export const GET_MEMBER = "GET_MEMBER";
export const CREATE_MEMBER = "CREATE_MEMBER";

export const SELECTED_CUSTOMER = "SELECTED_CUSTOMER";
export const RESET_SELECTED_CUSTOMER = "RESET_SELECTED_CUSTOMER";

export const CREATE_CLASSIC_SUPPORT = "CREATE_CLASSIC_SUPPORT";
export const GET_CLASSIC_SUPPORT = "GET_CLASSIC_SUPPORT";
export const UPDATE_CLASSIC_SUPPORT = "UPDATE_CLASSIC_SUPPORT";